---
- name: copy nginx repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: install nginx
  yum: name=nginx state=present
  notify: restart nginx

- name: copy default.conf
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
