title: RYNOTES
author: Ryoji Yoshioka
email: yoshioka.ryoji@gmail.com
description: GitHub を自然豊かな大草原にするために。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rynotes.com"
twitter_username: ojiry
github_username: ojiry
timezone: Asia/Tokyo
permalink: pretty

# Build settings
markdown: kramdown
exclude:
  - Capfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - config
  - log
  - s3_website.yml

sass:
  style: compressed

# Plugin settings
gems:
  - jekyll-sitemap
