version: '2'
services:
  ruby:
    image: ruby:2.3.1
    command: /bin/bash -c 'bundle install; bundle exec jekyll build'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app

  nginx:
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/blog/current/_site:/usr/share/nginx/html:ro
      - /etc/ssl:/etc/nginx/ssl
    depends_on:
      - 'ruby'
    restart: always
