---
- name: add gpg key
  rpm_key: state=present key=https://packages.treasuredata.com/GPG-KEY-td-agent

- name: add treasure data repository to yum
  copy: src=td.repo dest=/etc/yum.repos.d/td.repo

- name: install the toolbelt
  yum: name=td-agent state=present
  notify: restart td-agent

- name: install requirements package
  yum: name={{ item }} state=present
  with_items:
    - automake
    - libtool
    - gcc-c++
